### ISSUE TITLE
Impossible to use language detection now (?)

### ISSUE THREAD

**Issue by PiotrRomanskiPC** [i18next/next-i18next#1841]
## Is your feature request related to a problem? Please describe.
I'm trying to implement language detection based on query string. I tried to use `i18next-browser-languageDetector` but couldn't get it to work with the config file no matter what I tried. Then I wrote my own custom detector, the simplest I could come up with:

```JS
const languageDetector = {
  type: 'languageDetector',
  async: false,
  init: function (services, detectorOptions, i18nextOptions) {
    console.info('Inited language detector');
  },
  detect: function (callback) {
    console.info('Detected language: fr');
    return 'fr';
  },
  cacheUserLanguage: function (lng) {},
};
```
and I added it to `use` array in config. 

`init()` gets called, but `detect()` doesn't. I checked the source code and apparently the problem is that `next-i18next` requires `defaultLocale` property and then sets it as `lng` property of `i18next` config which disables language detection. So I guess it's completely impossible to use any language detector with this library currently?

## Describe the solution you'd like
Make it possible to use language detectors. If impossible with NextJS please state it somewhere in the docs clearly.

## Describe alternatives you've considered
I considered getting rid of NextJS...

## Additional context
This is the part of code that sets the `lng` property:

```JS
if (!locale) locale = userConfig.i18n.defaultLocale

      const instance = createClient({
        ...createConfig({
          ...userConfig,
          lng: locale,
        }),
        lng: locale,
        resources,
      }).i18n

      globalI18n = instance
```

This is the part of code in `i18next` which calls `.detect()` only if `lng` is not specified:

```JS
 if (!lng && this.services.languageDetector) lng = this.services.languageDetector.detect();
```

Maybe I get it totally wrong and it works. But I'm struggling with it for hours now, trying various solutions, SO answers and am more and more convinced that it's just impossible with current codebase.

**Comment by Hikmet-dev** [comment]
Hi!
I have the same problem, 3 days trying to set up [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) and every time a new problem.
I have several domains, there will be more in the future:
- exemple.com
- exemple.de
- exemple.es
- exemple.nl
- exemple.it
- exemple.fr
Basic settings next-i18next.config.js:
`{
  i18n: {
    defaultLocale: 'en-GB',
    locales: ['en-GB', 'de', 'fr', 'it', 'es', 'nl'],
    localeDetection: false,
    domains: [
      {
        domain: 'exemple.com',
        defaultLocale: 'en-GB',
      },
      {
        domain: 'exemple.de',
        defaultLocale: 'de',
      },
      {
        domain: 'exemple.es',
        defaultLocale: 'es',
      },
      {
        domain: 'exemple.nl',
        defaultLocale: 'nl',
      },
      {
        domain: 'exemple.fr',
        defaultLocale: 'fr',
      },
      {
        domain: 'exemple.it',
        defaultLocale: 'it',
      },
    ],
  },
  localePath: path.resolve('./public/locales'),
  react: { useSuspense: false },
  fallbackLng: ['en-GB'],
  serializeConfig: false,
}`

NextJS successfully switches between domains, but the problem is in the default language, it selects English every time.
Decided to use **i18next-browser-languagedetector** but can't get it set up.

### My custom detector:
`
const Domains = {
  'exemple.com': 'en-GB',
  'exemple.de': 'de',
  'exemple.es': 'es',
  'exemple.nl': 'nl',
  'exemple.it': 'it',
  'exemple.fr': 'fr',
};

const languageByDomainDetector = {
  name: 'domain',
  lookup(req, res, options) {
    let language = 'en-GB';
    if (typeof window !== 'undefined') {
      language = Domains[window.location.hostname];
    } else {
      language = Domains[req.get('host')];
    }

    return language;
  },
  cacheUserLanguage(lng, options) {},
};`

### Here are some configs of their error: 
First way:
Config:
`{
  i18n: {
    defaultLocale: 'en-GB',
    locales: ['en-GB', 'de', 'fr', 'it', 'es', 'nl'],
    localeDetection: false,
    domains: [
      {
        domain: 'exemple.com',
        defaultLocale: 'en-GB',
      },
      {
        domain: 'exemple.de',
        defaultLocale: 'de',
      },
      {
        domain: 'exemple.es',
        defaultLocale: 'es',
      },
      {
        domain: 'exemple.nl',
        defaultLocale: 'nl',
      },
      {
        domain: 'exemple.fr',
        defaultLocale: 'fr',
      },
      {
        domain: 'exemple.it',
        defaultLocale: 'it',
      },
    ],
  },
  localePath: path.resolve('./public/locales'),
  react: { useSuspense: false },
  fallbackLng: ['en-GB'],
  serializeConfig: false,
  use: [require('i18next-browser-languagedetector')],
  customDetectors: [languageByDomainDetector],
  detection: {
    order: ['domain'],
  },
};`

Error:
![image](https://user-images.githubusercontent.com/84195662/170676929-7d638bcb-3e9c-4cc1-8ffe-c662f803ef9d.png)

Second setup method:
`const LanguageDetector = require('i18next-browser-languagedetector').default;

const detector = new LanguageDetector(null, {
  order: ['domain'],
});
detector.addDetector(languageByDomainDetector);

module.exports = {
...
//without ->  customDetectors: [languageByDomainDetector],
//  detection: {
//    order: ['domain'],
//  },
  use: [detector],
...
}
`
Errors during build:
![image](https://user-images.githubusercontent.com/84195662/170678682-426fae5e-d897-46ea-b71c-ff6341a66fec.png)

Please tell me what is my mistake.

**Comment by eartho-group** [comment]
?

**Comment by dvird** [comment]
someone solved it?

**Comment by PiotrRomanskiPC** [comment]
We couldn't get the language detector to work so we fell back to use just default way of setting language, meaning putting culture in the path. For example instead of doing `http://example.com/blog/post/1?lang=en` we do `http://example.com/en/blog/post/1`. This seems to work out of the box.

Our full `next-i18next.config.js` looks like this:
```javascript
const I18NextHttpBackend = require('i18next-http-backend');

module.exports = {
  i18n: {
    defaultLocale: 'nl',
    locales: ['en', 'fr', 'nl'],
    preload: ['en', 'fr', 'nl'],
  },
  backend: {
    loadPath: `${process.env.NEXT_PUBLIC_REST_API_ENDPOINT}translations/{{lng}}/{{ns}}`,
  },
  serializeConfig: false,
  debug: false,
  ns: ['common'],
  use: [I18NextHttpBackend],
};
```

**Comment by stuart-williams** [comment]
Been having the same issue and the only way I could get custom language detection to work is to create a wrapper around `serverSideTranslations`. It might be completely terrible but middlewares legit don't work!

```typescript
import universalLanguageDetect from "@unly/universal-language-detector";
import type { GetServerSidePropsContext } from "next";
import NextCookies from "next-cookies";
import nextI18NextConfig, { i18n } from "next-i18next.config";
import { serverSideTranslations as _serverSideTranslations } from "next-i18next/serverSideTranslations";

export const serverSideTranslations = async (
  context: GetServerSidePropsContext,
  namespacesRequired = ["common"]
) => {
  const lng = context.query.lng as string;
  const locale = i18n.locales.includes(lng)
    ? lng
    : universalLanguageDetect({
        supportedLanguages: i18n.locales,
        serverCookies: NextCookies(context),
        fallbackLanguage: i18n.defaultLocale,
        acceptLanguageHeader: context.req.headers["accept-language"],
      });

  return _serverSideTranslations(locale, namespacesRequired, nextI18NextConfig);
};
```

**Comment by nickreese** [comment]
Thanks you @stuart-williams. Bummer the team closed this without a real answer.

**Comment by dmoz-ixl** [comment]
Would love to see this issue addressed/fixed. Not so much as a reply or keeping the issue open from the team, even though this is pretty clearly broken :/
