### ISSUE TITLE
reloadOnPrerender does not work

### ISSUE THREAD

**Issue by CommanderRedYT** [i18next/next-i18next#2123]
## 🐛 Bug Report

When setting `reloadOnPrerender` to `true` and changing words in the translation files (`public/locales/de/common.json` for example), NextJS will not reload the localization files.

## To Reproduce

(next dev)
1. Enable `reloadOnPrerender` in `next-i18next.config.js`.
2. Open the Page
3. Change one of the words used on the page (that are translated)
4. All other changes will hot-reload as normal, just the translated text will stay the same.

## Expected behavior

The little reload icon of NextJS should appear and the word should change.

## Your Environment

- *runtime version*: node v16.16.0 inside docker (image: node:16.16.0), Firefox 110.0.1
- *i18next version*: 22.4.11
- *next-i18next version*: 13.2.2
- *react-i18next version*: 12.2.0 (Not latest because SSR is broken)
- *os*: Linux

## Notes

When using `.js` files, which export the translations and importing / including that in the `resources` property, hot reloading works like normal, but probably cause NextJS reloads every changed `.js`-file

**Comment by adrai** [comment]
Are you also able to reproduce it in this example?

https://github.com/i18next/next-i18next/tree/master/examples/simple

**Comment by adrai** [comment]
btw: reloadOnPrerender is not like hot reload...

**Comment by CommanderRedYT** [comment]
> btw: reloadOnPrerender is not like hot reload...

Oh, well, is there a way then to hot reload?

**Comment by CommanderRedYT** [comment]
> Are you also able to reproduce it in this example?
> 
> https://github.com/i18next/next-i18next/tree/master/examples/simple

I have 99% the same like that (basically copied it)

**Comment by adrai** [comment]
Hot reload is done by next.js directly, so you may ask them.

**Comment by CommanderRedYT** [comment]
But it is supported by next-i18next (Like, you as the devs had it working), right?

**Comment by adrai** [comment]
Like said, reloadOnPrerender is not hot-reloading.
reloadOnPrerender will only serve new translations, when a new request is generated.
But if you only change the translations in the json file, there is nothing that will generate a new request, so you need to refresh the page manually.

**Comment by CommanderRedYT** [comment]
> Like said, reloadOnPrerender is not hot-reloading. reloadOnPrerender will only serve new translations, when a new request is generated. But if you only change the translations in the json file, there is nothing that will generate a new request, so you need to refresh the page manually.

Well, I tried that and reloaded the page (F5), and it still did not work

**Comment by adrai** [comment]
Here it works: https://github.com/i18next/next-i18next/tree/master/examples/simple

**Comment by karthikn2510** [comment]
> > Like said, reloadOnPrerender is not hot-reloading. reloadOnPrerender will only serve new translations, when a new request is generated. But if you only change the translations in the json file, there is nothing that will generate a new request, so you need to refresh the page manually.
> 
> Well, I tried that and reloaded the page (F5), and it still did not work

Hi CommanderRedYT, You can use i18next.reloadResources(); option before the return translation data, it will solve your problem without restart the server.
ref: https://www.i18next.com/overview/api#reloadresources

**Comment by shreyventure** [comment]
Hi @adrai , I cloned `examples/pages-router-simple` at master, ran `next dev`, edited `public/locales/en/common.json`, and hard-refreshed several times. **The change does not appear** until `next dev` is restarted. Same symptom @CommanderRedYT reported.

I traced the cause through the source. There are two server-side i18next instances on the pagesRouter path:

1. **`globalInstance`** ([`src/pagesRouter/createClient/node.ts`](https://github.com/i18next/next-i18next/blob/master/src/pagesRouter/createClient/node.ts)) — created on the first SSR request, reads locale JSON from disk via the auto-attached fs backend, then is `cloneInstance()`'d for every later request. Clones share its resource store by reference. **This is the cache that fills `pageProps._nextI18Next.initialI18nStore` and ultimately what the browser sees.**

2. **`globalI18n`** ([`src/pagesRouter/appWithTranslation.tsx`](https://github.com/i18next/next-i18next/blob/master/src/pagesRouter/appWithTranslation.tsx)) — populated by `appWithTranslation`'s `useMemo`, via `createClient/browser`.

In [`serverSideTranslations.ts`](https://github.com/i18next/next-i18next/blob/master/src/pagesRouter/serverSideTranslations.ts), `reloadOnPrerender` does:

```ts
if (reloadOnPrerender) await globalI18n?.reloadResources()
```
That targets `globalI18n`, but the translations actually delivered to the browser come from `globalInstance` (disk → globalInstance → pageProps → browser). 

The fix should be reloading `globalInstance` (or call reloadResources() on the just-cloned instance from line 33) instead of `globalI18n`.

**Comment by adrai** [comment]
Thanks @shreyventure — your diagnosis was spot on. Fixed in v16.0.6: the Pages Router now reloads on the node-side instance, scoped to exactly the locales × namespaces being shipped, and gated to `NODE_ENV !== 'production'` so custom HTTP/locize/chained backends aren't refetched per-request in prod. The App Router's `reloadOnPrerender` is now wired up too with the same dev-only semantics.
